// © 2025 Joseph MULÉ – M1SSION™
// Intelligence Analyst Templates - 250 response templates

export const ANALYST_TEMPLATES: Record<string, string[]> = {
  classify: [
    "Questi indizi sembrano convergere su un tema comune.",
    "Potrei dividerli in due categorie principali: luogo e premio.",
    "Alcuni indizi parlano di costruzioni, altri di simboli.",
    "Qui noto riferimenti sia a elementi moderni che storici.",
    "Sembrano frammenti collegati da un filo logico sottile.",
    "Suggerisco di separarli in base al tempo: passato e presente.",
    "Un paio di questi indizi parlano chiaramente di movimento.",
    "Classificherei questo gruppo come 'visivo' e l'altro come 'concettuale'.",
    "Ci sono allusioni a colori e forme, vale la pena raggrupparle.",
    "Alcuni elementi puntano verso un contesto naturale, altri artificiale.",
    "Indizi geografici da un lato, indizi simbolici dall'altro.",
    "Separerei quelli che parlano di luce da quelli che parlano di materia.",
    "Questo insieme mi sembra raccontare una progressione temporale.",
    "Un indizio ha natura numerica, lo metterei a parte.",
    "Direi che due di questi parlano di prestigio, gli altri di località.",
    "Li dividerei in indizi certi e indizi ambigui.",
    "Questi sono di tipo diretto, mentre gli altri sono più metaforici.",
    "Qui c'è una categoria legata alla tecnologia.",
    "Separerei ciò che evoca forza da ciò che evoca bellezza.",
    "Mi sembra che alcuni parlino di un viaggio.",
    "Questi due parlano di tempo, non di spazio.",
    "C'è una linea di pensiero che lega tre di loro, il resto è dispersivo.",
    "Indizi descrittivi vs indizi cifrati: buona separazione.",
    "Un paio citano oggetti concreti, altri sensazioni.",
    "Due parlano di Italia, gli altri no.",
    "Classificazione tematica: arte, scienza, territorio.",
    "Separerei quelli con numeri da quelli senza.",
    "Un indizio pare un titolo, gli altri sono descrizioni.",
    "Uno solo è fuorviante: lo segnerei come 'anomalo'.",
    "Indizi generici e indizi raffinati: netta differenza.",
    "Questi due hanno in comune una figura geometrica.",
    "Qui c'è chiaro un contrasto: luce vs ombra.",
    "Separerei 'premio' da 'luogo' in questo blocco.",
    "Classificazione secondo livello di dettaglio: basso/medio/alto.",
    "Alcuni hanno tono poetico, altri tecnico.",
    "Questi tre parlano di grandezza, gli altri di precisione.",
    "Un paio evocano velocità.",
    "Ci sono indizi sensoriali e indizi logici.",
    "Separerei i simbolici dai diretti.",
    "Due hanno un linguaggio molto simile, segno che vanno insieme.",
    "Uno sembra uno slogan, gli altri no.",
    "Indizi urbanistici da una parte, naturali dall'altra.",
    "Questi tre parlano chiaramente di energia.",
    "Ci sono parole chiave ripetute, le raggrupperei.",
    "Separerei i dettagli visivi dai dettagli storici.",
    "Uno pare ironico, differente dagli altri.",
    "Tre parlano di eleganza, gli altri di forza.",
    "Li vedo divisi per tipologia: cifrati e narrativi.",
    "Classificherei un paio come 'trappole'.",
    "Direi che qui abbiamo un mix di premi e località."
  ],
  patterns: [
    "Intravedo un filo rosso che unisce almeno tre indizi.",
    "Questi due condividono una stessa parola chiave.",
    "Vedo una ripetizione di concetti legati alla luce.",
    "C'è un pattern numerico nascosto qui.",
    "Due indizi hanno la stessa struttura grammaticale.",
    "Sembrano variazioni sullo stesso tema.",
    "Noto una progressione temporale: inizio, sviluppo, fine.",
    "Più indizi parlano di altezza.",
    "Qui ricorre un colore specifico.",
    "Tre citano elementi metallici.",
    "Due parlano di rumore, gli altri di silenzio.",
    "Noto un'alternanza costante: positivo/negativo.",
    "C'è un parallelismo tra il primo e l'ultimo.",
    "Tre fanno riferimento a velocità.",
    "Un pattern di direzione: nord, sud, movimento.",
    "Qui tornano riferimenti al lusso.",
    "Più di uno menziona acqua in forme diverse.",
    "Gli indizi sembrano formare una sequenza.",
    "Alcuni evocano dualità: interno/esterno.",
    "Ci sono due sinonimi che non credo casuali.",
    "Un ritmo ternario emerge qui.",
    "Molti sembrano giocare con la simmetria.",
    "Questo ricorda uno schema codificato.",
    "Due hanno struttura domanda-risposta.",
    "Un pattern fonetico appare evidente.",
    "Pare ci sia una rima nascosta.",
    "Ci sono simboli ricorrenti: cerchio, quadrato.",
    "Una logica binaria si ripete.",
    "Noto ridondanza intenzionale.",
    "Gli indizi formano una spirale concettuale.",
    "Due appaiono come eco l'uno dell'altro.",
    "Un ciclo: inizio e ritorno sullo stesso punto.",
    "Gli indizi richiamano stagioni.",
    "Sembrano tre varianti dello stesso messaggio.",
    "Una simmetria perfetta: 2 e 4 sono equivalenti.",
    "Noto parallelismi narrativi.",
    "Ritrovo la stessa parola spezzata in due indizi.",
    "Gli indizi si rispondono tra loro.",
    "Formano un mosaico coerente.",
    "Sembrano tessere di puzzle.",
    "Un pattern musicale: ritmo implicito.",
    "Vedo legami tra suoni ripetuti.",
    "Gli indizi hanno struttura speculare.",
    "Due paiono anagrammi l'uno dell'altro.",
    "Un gioco di opposizioni si ripete.",
    "Pattern nascosto: prima lettera di ogni indizio.",
    "Una logica circolare emerge.",
    "Sembrano messaggi in codice collegati.",
    "Il tema della luce ritorna tre volte.",
    "Un filo conduttore: innovazione."
  ],
  decode: [
    "Proverei un semplice cifrario di Cesare.",
    "Potrebbe trattarsi di un anagramma.",
    "Forse i numeri sono ASCII.",
    "Questo ricorda un codice Base64.",
    "Il pattern sembra binario.",
    "Puoi provare a invertirne le lettere.",
    "Mi ricorda un codice Morse.",
    "Forse ogni numero è un mese.",
    "Un codice semplice: sostituzione.",
    "Penso a coordinate nascoste.",
    "Magari è un acronimo.",
    "Potrebbe essere un rebus.",
    "Forse vanno letti al contrario.",
    "Sembrano coordinate criptate.",
    "Un classico: ROT13.",
    "Può essere un codice telefonico.",
    "Ci vedo lettere romane.",
    "Potrebbe celare un nome noto.",
    "Forse è un palindromo.",
    "Ricorda un puzzle crittografico.",
    "Potresti dividerlo in coppie.",
    "Forse sono sillabe invertite.",
    "Magari è un acrostico.",
    "Questo pare un codice alfanumerico.",
    "Può essere una sostituzione monoalfabetica.",
    "Indizio numerico = cifrario banale.",
    "Prova con dizionario anagrammi.",
    "Magari nasconde parole in più lingue.",
    "Potrebbe essere una frase spezzata.",
    "Forse devi sommare i numeri.",
    "Sembrano coordinate con offset.",
    "Potrebbe essere codice QR.",
    "Forse parole tronche.",
    "Un linguaggio simbolico.",
    "Pare un rebus figurato.",
    "Può essere un codice di trasporto.",
    "Sembra una chiave numerica.",
    "Forse cifrario polibio.",
    "Codice gematria?",
    "Può essere fonetico.",
    "Pare crittografia basica.",
    "Pensa a traslitterazione.",
    "Un rebus fonetico.",
    "Può essere con sostituzione vocali.",
    "Forse una sequenza Fibonacci.",
    "Magari vanno sommati i caratteri.",
    "Pare stringa codificata.",
    "Codice musicale?",
    "Coordinate travestite da numeri."
  ],
  probability: [
    "Direi che la probabilità è incerta ma crescente.",
    "Al momento sei a uno stadio iniziale.",
    "Le chance migliorano con più indizi.",
    "Direi che il rischio di errore è alto.",
    "La probabilità non è quantificabile con precisione.",
    "In questa fase il margine d'errore è elevato.",
    "Ogni indizio aumenta leggermente le tue chance.",
    "La tua posizione è ancora fragile.",
    "Direi che hai poche certezze.",
    "Siamo in un territorio incerto.",
    "Più indizi = più probabilità.",
    "La fiducia cresce lentamente.",
    "Ti trovi al 30% del cammino.",
    "Ci sono variabili fuori controllo.",
    "Le probabilità migliorano di poco.",
    "Direi che resti sotto il 50%.",
    "La tua traiettoria è promettente.",
    "Il rischio è ancora notevole.",
    "Sei sulla strada giusta, ma incompleta.",
    "Ogni connessione aumenta la tua forza.",
    "La probabilità resta bassa.",
    "Hai raggiunto un punto intermedio.",
    "La stima è positiva, ma prudente.",
    "Sei in zona di rischio medio.",
    "Ogni errore pesa molto ora.",
    "La probabilità cresce con logica cumulativa.",
    "Le tue chance dipendono dai prossimi passi.",
    "Valuto rischio medio-alto.",
    "Direi incertezza dominante.",
    "La fiducia sale, ma lentamente.",
    "Resti in zona neutra.",
    "Le probabilità sono migliorate rispetto a prima.",
    "Un passo avanti, ma non ancora decisivo.",
    "Ancora presto per stimare seriamente.",
    "Direi che il cammino resta lungo.",
    "La probabilità si alza col tempo.",
    "Hai basi fragili ma promettenti.",
    "La tua posizione si è rafforzata.",
    "Ora la stima è più ottimista.",
    "Hai costruito credibilità investigativa.",
    "Il rischio resta alto.",
    "Una chance su tre.",
    "Probabilità attorno al 40%.",
    "Ti avvicini alla soglia critica.",
    "Ancora incertezza diffusa.",
    "Direi che sei sulla giusta traiettoria.",
    "La probabilità cresce, resta vigile.",
    "Hai migliorato le tue possibilità.",
    "Valutazione prudente: medio-bassa.",
    "Sei in crescita costante."
  ],
  mentor: [
    "Non mollare, sei sulla strada giusta.",
    "Ogni indizio è un passo verso la verità.",
    "La pazienza è la tua arma segreta.",
    "Non avere fretta: ogni dettaglio conta.",
    "Il gioco premia chi sa osservare.",
    "Continua a cercare, anche nei dettagli minimi.",
    "La tua dedizione ti porterà lontano.",
    "Non sottovalutare mai un piccolo segno.",
    "Ogni indizio ha un valore nascosto.",
    "Il percorso è tanto importante quanto la meta.",
    "Non lasciarti ingannare dai falsi segnali.",
    "Sii freddo come un analista.",
    "Ma anche curioso come un esploratore.",
    "Non smettere di collegare i punti.",
    "Ricorda: l'apparenza inganna.",
    "Ogni errore è un passo di apprendimento.",
    "Mantieni la mente aperta.",
    "Il tuo intuito è parte della strategia.",
    "Non ti arrendere ai primi ostacoli.",
    "Ogni dettaglio può essere chiave.",
    "Sii metodico, ma anche creativo.",
    "Le risposte arrivano a chi sa attendere.",
    "La tua tenacia farà la differenza.",
    "Non lasciarti distrarre.",
    "Segui la logica, ma ascolta anche l'istinto.",
    "Cerca l'armonia nei dettagli.",
    "Non abbandonare la pista.",
    "Tieni alta la concentrazione.",
    "Ogni giorno può portare un indizio nuovo.",
    "La calma è la tua forza.",
    "Sii pronto a cambiare prospettiva.",
    "Il viaggio vale più della destinazione.",
    "La caccia è parte della vittoria.",
    "Non dimenticare di osservare tutto.",
    "Sii costante, ma anche elastico.",
    "Il mistero si risolve un passo alla volta.",
    "Ogni indizio è un tassello del mosaico.",
    "Non lasciare nulla al caso.",
    "Sii vigile e attento.",
    "Ricorda: il tempo è un alleato.",
    "La determinazione è la chiave.",
    "Non dubitare del tuo percorso.",
    "La forza è nella pazienza.",
    "Segui la traccia con fiducia.",
    "Ogni segnale è prezioso.",
    "Non smettere di interrogare i dettagli.",
    "Mantieni la mente affilata.",
    "La vittoria è per chi persevera.",
    "Il mistero si svela a chi insiste.",
    "Tu puoi farcela."
  ]
};
