/// <reference lib="webworker" />
// © 2025 Joseph MULÉ – CEO di NIYVORA KFT™
// M1SSION™ Service Worker - PWA Caching Strategy
// Note: Workbox imports temporarily disabled to resolve build issues
// import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
// import { registerRoute } from 'workbox-routing';
// import { NetworkFirst, CacheFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

// Precache all the assets generated by your build process
// precacheAndRoute((self as any).__WB_MANIFEST);

// Clean up outdated caches
// cleanupOutdatedCaches();

// Cache API calls with NetworkFirst strategy
// registerRoute(
//   ({ url }) => url.origin === 'https://vkjrqirvdvjbemsfzxof.supabase.co',
//   new NetworkFirst({
//     cacheName: 'supabase-api-cache',
//     networkTimeoutSeconds: 10,
//   })
// );

// Cache static assets with CacheFirst strategy
// registerRoute(
//   ({ request }) => request.destination === 'image',
//   new CacheFirst({
//     cacheName: 'images-cache',
//   })
// );

// Cache CSS and JS files
// registerRoute(
//   ({ request }) => request.destination === 'style' || request.destination === 'script',
//   new CacheFirst({
//     cacheName: 'static-assets-cache',
//   })
// );

// Handle offline fallback
// registerRoute(
//   ({ request }) => request.mode === 'navigate',
//   new NetworkFirst({
//     cacheName: 'pages-cache',
//     networkTimeoutSeconds: 3,
//   })
// );

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('install', (event) => {
  console.log('M1SSION™ Service Worker installed');
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  console.log('M1SSION™ Service Worker activated');
  event.waitUntil(self.clients.claim());
});

// Push notification handler - iOS compatible
self.addEventListener('push', (event) => {
  console.log('🔔 SW: Push event received:', event);
  console.log('🔔 SW: Event data available:', !!event.data);
  
  if (!event.data) {
    console.log('🔔 SW: No data in push event - showing fallback notification');
    event.waitUntil(
      self.registration.showNotification('M1SSION™', {
        body: 'Nuova notifica disponibile',
        icon: '/favicon.ico',
        badge: '/favicon.ico',
        requireInteraction: true,
        data: { url: '/notifications' },
        tag: 'mission-fallback'
      })
    );
    return;
  }
  
  try {
    const data = event.data.json();
    console.log('🔔 SW: Push data parsed:', data);
    
    // ✅ CRITICAL FIX: Handle both direct payload and nested data structures
    const notificationData = data.notification || data;
    const title = notificationData.title || data.title || 'M1SSION™';
    const body = notificationData.body || data.body || 'Nuova notifica da M1SSION™';
    
    console.log(`🔔 SW: Extracted - Title: "${title}", Body: "${body}"`);
    
    const options: NotificationOptions = {
      body: body,
      icon: '/favicon.ico',
      badge: '/favicon.ico',
      data: {
        url: '/notifications',
        timestamp: new Date().toISOString(),
        source: 'push_notification',
        ...data.data
      },
      tag: data.tag || 'mission-notification',
      silent: false,
      requireInteraction: true, // iOS compatibility
      dir: 'ltr' as NotificationDirection,
      lang: 'it'
    };

    console.log('🔔 SW: Showing notification with options:', options);
    
    event.waitUntil(
      self.registration.showNotification(title, options)
        .then(() => {
          console.log('🔔 SW: Notification shown successfully');
          // ✅ Send message to main thread to update UI
          self.clients.matchAll().then(clients => {
            clients.forEach(client => {
              client.postMessage({
                type: 'PUSH_NOTIFICATION_RECEIVED',
                data: { title, body, timestamp: new Date().toISOString() }
              });
            });
          });
        })
        .catch((error) => {
          console.error('🔔 SW: Error showing notification:', error);
        })
    );
  } catch (error) {
    console.error('🔔 SW: Push notification parsing error:', error);
    // Fallback notification with iOS compatibility
    event.waitUntil(
      self.registration.showNotification('M1SSION™', {
        body: 'Nuova notifica disponibile',
        icon: '/favicon.ico',
        badge: '/favicon.ico',
        requireInteraction: true,
        data: { url: '/notifications' },
        tag: 'mission-fallback'
      })
    );
  }
});

// Notification click handler - iOS compatible
self.addEventListener('notificationclick', (event) => {
  console.log('🔔 SW: Notification clicked:', event);
  
  event.notification.close();
  
  const urlToOpen = event.notification.data?.url || '/notifications';
  console.log('🔔 SW: Opening URL:', urlToOpen);
  
  event.waitUntil(
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true
    }).then((clientList) => {
      console.log('🔔 SW: Found clients:', clientList.length);
      
      // Check if app is already open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          console.log('🔔 SW: Focusing existing client and navigating to:', urlToOpen);
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      
      // Open new window if app not open
      if (self.clients.openWindow) {
        console.log('🔔 SW: Opening new window:', urlToOpen);
        return self.clients.openWindow(urlToOpen);
      }
    }).catch((error) => {
      console.error('🔔 SW: Error handling notification click:', error);
    })
  );
});