-- ============================================
-- M1SSION™ P0 Backend Migration
-- RLS Hardening + Winners Real Data + Cron Logs
-- © 2025 Joseph MULÉ – M1SSION™
-- ============================================

-- ============================================
-- TASK 1: RLS HARDENING (Profiles & Payments)
-- ============================================

-- 1.1) Protect profiles table
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Remove overly permissive public policy
DROP POLICY IF EXISTS "Public profiles are viewable" ON profiles;

-- Users can only SELECT/UPDATE their own profile
CREATE POLICY "Users select own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- 1.2) Create public_profiles view with safe fields only
DROP VIEW IF EXISTS public_profiles CASCADE;
CREATE VIEW public_profiles AS
SELECT
  id,
  agent_code,
  nickname,
  avatar_url,
  investigative_style,
  rank_id,
  created_at
FROM profiles;

-- Grant public read access to safe view
GRANT SELECT ON public_profiles TO anon, authenticated;

-- 1.3) Protect payment_transactions table (if exists)
DO $$ 
BEGIN
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'payment_transactions') THEN
    ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;
    
    -- Users can only view own transactions
    DROP POLICY IF EXISTS "Users select own payments" ON payment_transactions;
    CREATE POLICY "Users select own payments"
      ON payment_transactions FOR SELECT
      USING (auth.uid() = user_id);
    
    -- Admin override (if user_roles exists)
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'user_roles') THEN
      DROP POLICY IF EXISTS "Admins can select all payments" ON payment_transactions;
      CREATE POLICY "Admins can select all payments"
        ON payment_transactions FOR SELECT
        USING (
          EXISTS (
            SELECT 1 FROM user_roles
            WHERE user_roles.user_id = auth.uid()
              AND user_roles.role = 'admin'
          )
        );
    END IF;
  END IF;
END $$;

-- ============================================
-- TASK 2: WINNERS REAL DATA (final_shots)
-- ============================================

-- 2.1) Create final_shots table
CREATE TABLE IF NOT EXISTS final_shots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mission_id UUID REFERENCES missions(id) ON DELETE SET NULL,
  winner_user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  prize_id UUID REFERENCES prizes(id) ON DELETE SET NULL,
  completion_time TIMESTAMPTZ NOT NULL DEFAULT now(),
  proof_url TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on final_shots
ALTER TABLE final_shots ENABLE ROW LEVEL SECURITY;

-- Service role only for writes (security)
REVOKE ALL ON final_shots FROM anon, authenticated;

-- 2.2) Create winners_public view
DROP VIEW IF EXISTS winners_public CASCADE;
CREATE VIEW winners_public AS
SELECT
  fs.id,
  fs.mission_id,
  fs.prize_id,
  fs.completion_time,
  fs.winner_user_id,
  pp.agent_code,
  pp.nickname,
  pp.avatar_url,
  pr.name AS prize_title
FROM final_shots fs
LEFT JOIN public_profiles pp ON pp.id = fs.winner_user_id
LEFT JOIN prizes pr ON pr.id = fs.prize_id
ORDER BY fs.completion_time DESC;

-- Grant public read access to winners view
GRANT SELECT ON winners_public TO anon, authenticated;

-- ============================================
-- TASK 3: CRON LOGGING TABLE
-- ============================================

-- 3.1) Create cron_logs table for monitoring
CREATE TABLE IF NOT EXISTS cron_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job TEXT NOT NULL,
  status TEXT NOT NULL,
  payload JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on cron_logs
ALTER TABLE cron_logs ENABLE ROW LEVEL SECURITY;

-- Admin-only access to cron logs
CREATE POLICY "Admins can view cron logs"
  ON cron_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_roles.user_id = auth.uid()
        AND user_roles.role = 'admin'
    )
  );

-- Service role can insert cron logs
CREATE POLICY "Service role can insert cron logs"
  ON cron_logs FOR INSERT
  WITH CHECK (true);

-- ============================================
-- VERIFICATION QUERIES (READ-ONLY)
-- ============================================

-- Verify profiles RLS is active
SELECT schemaname, tablename, rowsecurity
FROM pg_tables
WHERE tablename = 'profiles';

-- Verify public_profiles view exists
SELECT table_name, view_definition
FROM information_schema.views
WHERE table_schema = 'public'
  AND table_name = 'public_profiles';

-- Verify final_shots table exists
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'final_shots';

-- Verify winners_public view exists
SELECT table_name, view_definition
FROM information_schema.views
WHERE table_schema = 'public'
  AND table_name = 'winners_public';

-- © 2025 Joseph MULÉ – M1SSION™ – ALL RIGHTS RESERVED – NIYVORA KFT™