-- © 2025 Joseph MULÉ – M1SSION™ – P1 Backend Support
-- push_delivery_logs table for E2E diagnostics

CREATE TABLE IF NOT EXISTS push_delivery_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  channel text NOT NULL CHECK (channel IN ('webpush', 'fcm', 'apns')),
  message_tag text,
  status text NOT NULL CHECK (status IN ('queued', 'sent', 'delivered', 'failed')),
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- RLS for push_delivery_logs
ALTER TABLE push_delivery_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own push logs"
  ON push_delivery_logs FOR SELECT
  USING (auth.uid() = user_id);

-- Index for performance
CREATE INDEX idx_push_logs_user_status ON push_delivery_logs(user_id, status, created_at DESC);

-- © 2025 Joseph MULÉ – M1SSION™ – ALL RIGHTS RESERVED – NIYVORA KFT™