-- © 2025 Joseph MULÉ – M1SSION™ – Living Map Phase 1 Migration

-- PULSE: Global energy state (singleton)
CREATE TABLE IF NOT EXISTS public.pulse_state (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value        INTEGER NOT NULL DEFAULT 0 CHECK (value >= 0 AND value <= 100),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert singleton row if not exists
INSERT INTO public.pulse_state (value)
SELECT 0 WHERE NOT EXISTS (SELECT 1 FROM public.pulse_state);

-- Realtime notification function
CREATE OR REPLACE FUNCTION public.fn_pulse_notify()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_notify('pulse_update', json_build_object(
    'value', NEW.value,
    'updated_at', NEW.updated_at
  )::text);
  RETURN NEW;
END;
$$;

-- Trigger for pulse updates
DROP TRIGGER IF EXISTS trg_pulse_notify ON public.pulse_state;
CREATE TRIGGER trg_pulse_notify
AFTER UPDATE ON public.pulse_state
FOR EACH ROW EXECUTE FUNCTION public.fn_pulse_notify();

-- DNA: Agent profile parameters
CREATE TABLE IF NOT EXISTS public.agent_dna (
  user_id      UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  intuito      INTEGER NOT NULL DEFAULT 50 CHECK (intuito BETWEEN 0 AND 100),
  audacia      INTEGER NOT NULL DEFAULT 50 CHECK (audacia BETWEEN 0 AND 100),
  etica        INTEGER NOT NULL DEFAULT 50 CHECK (etica BETWEEN 0 AND 100),
  rischio      INTEGER NOT NULL DEFAULT 50 CHECK (rischio BETWEEN 0 AND 100),
  vibrazione   INTEGER NOT NULL DEFAULT 50 CHECK (vibrazione BETWEEN 0 AND 100),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for agent_dna
ALTER TABLE public.agent_dna ENABLE ROW LEVEL SECURITY;

-- RLS Policies for agent_dna
DROP POLICY IF EXISTS dna_owner_select ON public.agent_dna;
CREATE POLICY dna_owner_select ON public.agent_dna
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS dna_owner_insert ON public.agent_dna;
CREATE POLICY dna_owner_insert ON public.agent_dna
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS dna_owner_update ON public.agent_dna;
CREATE POLICY dna_owner_update ON public.agent_dna
  FOR UPDATE USING (auth.uid() = user_id);

-- Helper function: ensure DNA exists for user
CREATE OR REPLACE FUNCTION public.ensure_agent_dna(p_user UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.agent_dna(user_id) 
  VALUES (p_user)
  ON CONFLICT (user_id) DO NOTHING;
END;
$$;

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION public.update_agent_dna_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_agent_dna_timestamp ON public.agent_dna;
CREATE TRIGGER trg_agent_dna_timestamp
BEFORE UPDATE ON public.agent_dna
FOR EACH ROW EXECUTE FUNCTION public.update_agent_dna_timestamp();