-- © 2025 Joseph MULÉ – M1SSION™ – ALL RIGHTS RESERVED – NIYVORA KFT™
-- Stub tables to unblock types.ts and fix build errors
-- All tables have restrictive RLS (deny by default) - features remain disabled

-- 1) Abuse logs (contact form / anti-spam - stub)
CREATE TABLE IF NOT EXISTS public.abuse_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  message TEXT,
  meta JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.abuse_logs ENABLE ROW LEVEL SECURITY;

-- Owner can read their own abuse logs
CREATE POLICY "Owner read abuse logs" 
ON public.abuse_logs 
FOR SELECT 
USING (auth.uid() = user_id);

-- 2) API rate limits (stub)
CREATE TABLE IF NOT EXISTS public.api_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  route TEXT NOT NULL,
  hits INT NOT NULL DEFAULT 0,
  reset_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '1 hour',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;

-- Owner can read their own rate limits
CREATE POLICY "Owner read api rates" 
ON public.api_rate_limits 
FOR SELECT 
USING (auth.uid() = user_id);

-- 3) Minigames progress (stub)
CREATE TABLE IF NOT EXISTS public.user_minigames_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  game_key TEXT NOT NULL,
  progress_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.user_minigames_progress ENABLE ROW LEVEL SECURITY;

-- Owner can read their own minigames progress
CREATE POLICY "Owner read minigames" 
ON public.user_minigames_progress 
FOR SELECT 
USING (auth.uid() = user_id);

-- 4) Battles (stub - feature hard-locked/disabled)
CREATE TABLE IF NOT EXISTS public.battles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status TEXT NOT NULL DEFAULT 'disabled',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.battle_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  battle_id UUID REFERENCES public.battles(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.battles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.battle_metrics ENABLE ROW LEVEL SECURITY;

-- NO policies for battles/battle_metrics → completely locked (feature disabled)

-- Lightweight indices for potential debug queries
CREATE INDEX IF NOT EXISTS idx_api_rate_limits_user_route 
ON public.api_rate_limits(user_id, route);

CREATE INDEX IF NOT EXISTS idx_minigames_user_game 
ON public.user_minigames_progress(user_id, game_key);

-- © 2025 Joseph MULÉ – M1SSION™ – ALL RIGHTS RESERVED – NIYVORA KFT™