
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = "https://vkjrqirvdvjbemsfzxof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZranJxaXJ2ZHZqYmVtc2Z6eG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzQyMjYsImV4cCI6MjA2MDYxMDIyNn0.rb0F3dhKXwb_110--08Jsi4pt_jx-5IWwhi96eYMxBk";

// Configurazione specifica per iOS WebView
const isIOS = Capacitor.getPlatform() === 'ios';
const supabaseClientOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: localStorage,
    storageKey: 'supabase.auth.token',
  }
};

// Log di debug per problemi di sessione iOS
if (isIOS) {
  console.log("📱 Configurazione Supabase potenziata per iOS WebView");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  supabaseClientOptions
);

// Debug sessione iniziale per iOS
if (isIOS) {
  setTimeout(async () => {
    try {
      const { data } = await supabase.auth.getSession();
      console.log("🧪 iOS Debug - Sessione iniziale:", data.session ? "Presente" : "Assente");
    } catch (err) {
      console.error("🧪 iOS Debug - Errore lettura sessione:", err);
    }
  }, 1000);
}
