// © 2025 Joseph MULÉ – M1SSION™ – ALL RIGHTS RESERVED – NIYVORA KFT™

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Mail, User, Shield } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

interface PreRegistrationFormProps {
  onSuccess?: () => void;
  onCancel?: () => void;
}

export const PreRegistrationForm: React.FC<PreRegistrationFormProps> = ({
  onSuccess,
  onCancel
}) => {
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handlePreRegistration = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!email || !name) {
      toast.error('Compila tutti i campi obbligatori');
      return;
    }

    setIsLoading(true);
    
    try {
      // Insert into pre_registered_users table
      const { data, error } = await supabase
        .from('pre_registered_users')
        .insert({
          email: email.toLowerCase(),
          // Agent code will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) {
        if (error.code === '23505') { // Unique constraint violation
          toast.error('Email già registrata per l\'accesso anticipato');
          return;
        }
        throw error;
      }

      toast.success('Pre-registrazione completata!', {
        description: `Codice agente: ${data.agent_code}. Ti invieremo una email quando sarà il momento dell'accesso.`
      });

      // Call success callback
      onSuccess?.();

    } catch (error: any) {
      console.error('❌ Errore pre-registrazione:', error);
      toast.error('Errore durante la pre-registrazione');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="glass-card p-6 backdrop-blur-md border border-gray-800 rounded-xl">
      <div className="text-center mb-6">
        <div className="w-12 h-12 bg-gradient-to-br from-cyan-400 to-primary rounded-full flex items-center justify-center mx-auto mb-4">
          <Shield className="w-6 h-6 text-white" />
        </div>
        <h3 className="text-xl font-bold text-white mb-2">Pre-Registrazione M1SSION™</h3>
        <p className="text-gray-400 text-sm">
          Ottieni accesso prioritario e il tuo codice agente univoco
        </p>
      </div>

      <form onSubmit={handlePreRegistration} className="space-y-4">
        <div className="relative">
          <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
          <Input
            type="text"
            placeholder="Nome completo"
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="pl-10 glass-input"
            required
          />
        </div>

        <div className="relative">
          <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
          <Input
            type="email"
            placeholder="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="pl-10 glass-input"
            required
          />
        </div>

        <div className="flex gap-3">
          <Button
            type="submit"
            disabled={isLoading}
            className="flex-1 bg-gradient-to-r from-cyan-500 to-primary hover:from-cyan-600 hover:to-primary/80 text-white font-semibold"
          >
            {isLoading ? 'Registrando...' : 'Pre-Registrati'}
          </Button>
          
          {onCancel && (
            <Button
              type="button"
              variant="outline"
              onClick={onCancel}
              className="px-6 border-gray-600 text-gray-300 hover:bg-gray-800"
            >
              Annulla
            </Button>
          )}
        </div>
      </form>

      <div className="mt-4 text-xs text-gray-500 text-center">
        <p>
          La pre-registrazione ti garantisce:
        </p>
        <ul className="mt-2 space-y-1">
          <li>🆔 Codice agente univoco</li>
          <li>📧 Notifica email di accesso</li>
          <li>⚡ Priorità nella coda di accesso</li>
        </ul>
      </div>
    </div>
  );
};